version: '3'
services:
  main_app:
    build:
      dockerfile: services/main_shiny/Dockerfile
    ports:
      - 8000:8000

#  app:
#    build: .
#    ports:
#      - "5000:5000"
#    depends_on:
#      - redis
#  redis:
#    image: redis:7-alpine
#  db:
#    image: keinos/sqlite3
