version: '3'
services:
  main_app:
    build:
      dockerfile: services/main_shiny/Dockerfile
    ports:
      - 8000:8000
  reports_app:
    build:
      dockerfile: services/reports/Dockerfile
    ports:
      - 8001:8000

