version: '3'
services:
  main_app:
    build:
      dockerfile: services/main_shiny/Dockerfile
    ports:
      - 8000:8000
    volumes:
#      - ./datasets:/mecon/datasets
      - "${DATASETS_DIR}:/mecon/datasets"
  reports_app:
    build:
      dockerfile: services/reports/Dockerfile
    ports:
      - 8001:8000
    volumes:
#      - ./datasets:/mecon/datasets
      - "${DATASETS_DIR}:/mecon/datasets"
  edit_data_app:
    build:
      dockerfile: services/edit_data/Dockerfile
    ports:
      - 8002:8000
    volumes:
#      - ./datasets:/mecon/datasets
      - "${DATASETS_DIR}:/mecon/datasets"

